### Import standard GDAL and NumPy packages

In [1]:
import numpy as np
from osgeo import gdal

### Import SKOPE data analysis functions

In [2]:
import skope.analysis as sa

### Set the location and name of the data set file to create

In [3]:
test_dataset_filename = '../data/monthly_5x5x60_dataset_int16_variable.tif'

### Create the test dataset file using a local utility function

In [4]:
dataset = sa.create_dataset(
    filename     = test_dataset_filename,
    format       = 'GTiff',
    pixel_type   = gdal.GDT_Int16, 
    rows         = 5, 
    cols         = 5, 
    bands        = 60,
    origin_x     = -123,
    origin_y     = 45,
    pixel_width  = 1, 
    pixel_height = 1
)

### Define the pixel values to be assigned to the first band of the data set

In [5]:
band_1_data = np.array([
    [100, 101, 102, 103, 104],
    [110, 111, 112, 113, 114],
    [120, 121, 122, 123, 124],
    [130, 131, 132, 133, 134],
    [140, 141, 142, 143, 144]
])

### Write pixel values to each band of the data set
For all bands other than the first, the value of each pixel is 100 more than the pixel directly below it in the previous band.

In [6]:
for i in range(0,60):
    sa.write_band(
        dataset = dataset,
        band    = i + 1,
        array   = band_1_data + i * 100,
        nodata  = 65535
    )

dataset.FlushCache()

### Confirm some expected pixel values in the new data set

In [7]:
assert sa.read_pixel(dataset,band=1,row=0,column=0) == 100
assert sa.read_pixel(dataset,band=1,row=4,column=4) == 144
assert sa.read_pixel(dataset,band=60,row=0,column=0) == 6000
assert sa.read_pixel(dataset,band=60,row=4,column=4) == 6044

### Display pixel values in each band of new data set for easy reference

In [8]:
for i in range(1,61):
    print("\nband", i, "\n", dataset.GetRasterBand(i).ReadAsArray())


band 1 
 [[100 101 102 103 104]
 [110 111 112 113 114]
 [120 121 122 123 124]
 [130 131 132 133 134]
 [140 141 142 143 144]]

band 2 
 [[200 201 202 203 204]
 [210 211 212 213 214]
 [220 221 222 223 224]
 [230 231 232 233 234]
 [240 241 242 243 244]]

band 3 
 [[300 301 302 303 304]
 [310 311 312 313 314]
 [320 321 322 323 324]
 [330 331 332 333 334]
 [340 341 342 343 344]]

band 4 
 [[400 401 402 403 404]
 [410 411 412 413 414]
 [420 421 422 423 424]
 [430 431 432 433 434]
 [440 441 442 443 444]]

band 5 
 [[500 501 502 503 504]
 [510 511 512 513 514]
 [520 521 522 523 524]
 [530 531 532 533 534]
 [540 541 542 543 544]]

band 6 
 [[600 601 602 603 604]
 [610 611 612 613 614]
 [620 621 622 623 624]
 [630 631 632 633 634]
 [640 641 642 643 644]]

band 7 
 [[700 701 702 703 704]
 [710 711 712 713 714]
 [720 721 722 723 724]
 [730 731 732 733 734]
 [740 741 742 743 744]]

band 8 
 [[800 801 802 803 804]
 [810 811 812 813 814]
 [820 821 822 823 824]
 [830 831 832 833 834]
 [840 841 842 84